# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad14a74191994ff7dc3132d5accdd34e39168b2c5eb5acf76b8c4b8496b1f2558fb36ef021b7319cd35ebea6ad51fc203c2c495b878ac60073fc8f8bed5f9cd

test:
  secret_key_base: 3b1b82b868a8445d19dabf12bc67df564479434913ad2a5cf10ffc410533731d611e486f2facd1b619b52a0df9ca1fda2feabd477626357963f19865f8166433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
